export { default as Help } from './Help';
export { default as Home } from './Home';
export { default as About } from './About';
export { default as Forum } from './Forum';
export { default as Error } from './Error';
export { default as Footer } from './Footer';
export { default as Contacts } from './Contacts';
export { default as TermsOfUse } from './TermsOfUse';
export { default as PrivacyPolice } from './PrivacyPolice';
