import {
  cardImg,
  cardImgTwo,
  highPostImg,
  cardImgThree,
  highPostTwoImg,
  highPostThreeImg,
  highPostFiveImg,
} from 'assets/img';
import { TEventCard } from 'components/shared/Cards/EventCard/types';

export const TournamentCardInfo: TEventCard[] = [
  {
    id: 1,
    img: highPostImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 2,
    img: cardImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 3,
    img: cardImgThree,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 4,
    img: cardImgTwo,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 5,
    img: highPostTwoImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 6,
    img: highPostThreeImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 7,
    img: highPostImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 8,
    img: cardImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 9,
    img: cardImgThree,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 10,
    img: cardImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 12,
    img: highPostFiveImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 13,
    img: cardImgThree,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 14,
    img: cardImgThree,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 15,
    img: highPostFiveImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 16,
    img: highPostThreeImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 17,
    img: highPostTwoImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 18,
    img: cardImgThree,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 19,
    img: cardImg,
    eventTitle: 'Tournament Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
];

export const EventCardInfo: TEventCard[] = [
  {
    id: 1,
    img: highPostImg,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 2,
    img: cardImgThree,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 3,
    img: cardImgTwo,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 4,
    img: highPostTwoImg,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 5,
    img: highPostThreeImg,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 6,
    img: cardImg,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 7,
    img: highPostImg,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 8,
    img: cardImgThree,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 9,
    img: cardImgTwo,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 10,
    img: cardImg,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 12,
    img: highPostFiveImg,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 13,
    img: cardImgThree,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 14,
    img: cardImgThree,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 15,
    img: highPostFiveImg,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 16,
    img: highPostThreeImg,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 17,
    img: highPostTwoImg,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 18,
    img: cardImgThree,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
  {
    id: 19,
    img: cardImg,
    eventTitle: 'Event Title Name',
    eventDate: 'September 29, 2022 - 11AM',
  },
];
