import { GuyImg, GuyImgTwo, UserImg, topUserImg, topUserThree, topUserTwo } from 'assets/img';

import { TPeopleCard } from './../../components/shared/Cards/PeopleCard/types';

export const userSearchCase: TPeopleCard[] = [
  {
    id: 1,
    userImg: GuyImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 2,
    userImg: GuyImgTwo,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 3,
    userImg: UserImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 4,
    userImg: topUserImg,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 5,
    userImg: GuyImgTwo,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 6,
    userImg: UserImg,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 7,
    userStatus: false,
    userImg: topUserImg,
    userName: 'Username',
    status: false,
  },
  {
    id: 8,
    userImg: GuyImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 9,
    userStatus: true,
    userImg: GuyImgTwo,
    userName: 'Username',
    status: false,
  },
  {
    id: 10,
    userImg: UserImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 11,
    userStatus: false,
    userImg: topUserThree,
    userName: 'Username',
    status: false,
  },
  {
    id: 12,
    userImg: UserImg,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 13,
    userImg: GuyImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 14,
    userStatus: false,
    userName: 'Username',
    userImg: topUserThree,
    status: false,
  },
  {
    id: 15,
    userStatus: false,
    userImg: GuyImgTwo,
    userName: 'Username',
    status: false,
  },

  {
    id: 16,
    userImg: GuyImgTwo,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 17,
    userImg: GuyImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 18,
    userImg: topUserImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 19,
    userImg: UserImg,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 20,
    userImg: GuyImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 21,
    userImg: GuyImgTwo,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 22,
    userStatus: false,
    userImg: UserImg,
    userName: 'Username',
    status: false,
  },
  {
    id: 23,
    userImg: GuyImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 24,
    userStatus: true,
    userImg: UserImg,
    userName: 'Username',
    status: false,
  },
  {
    id: 25,
    userImg: topUserImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 26,
    userStatus: false,
    userImg: topUserThree,
    userName: 'Username',
    status: false,
  },
  {
    id: 27,
    userImg: GuyImg,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 28,
    userImg: GuyImgTwo,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 29,
    userStatus: false,
    userName: 'Username',
    userImg: topUserThree,
    status: false,
  },
  {
    id: 30,
    userStatus: false,
    userImg: topUserTwo,
    userName: 'Username',
    status: false,
  },

  {
    id: 31,
    userImg: UserImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 32,
    userImg: GuyImgTwo,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 33,
    userImg: GuyImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 34,
    userImg: topUserTwo,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 35,
    userImg: GuyImgTwo,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 36,
    userImg: UserImg,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 37,
    userStatus: false,
    userImg: topUserImg,
    userName: 'Username',
    status: false,
  },
  {
    id: 38,
    userImg: topUserThree,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 39,
    userStatus: true,
    userImg: topUserTwo,
    userName: 'Username',
    status: false,
  },
  {
    id: 40,
    userImg: GuyImgTwo,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 41,
    userStatus: false,
    userImg: topUserThree,
    userName: 'Username',
    status: false,
  },
  {
    id: 42,
    userImg: UserImg,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 43,
    userImg: GuyImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 44,
    userStatus: false,
    userName: 'Username',
    userImg: topUserThree,
    status: false,
  },
  {
    id: 45,
    userStatus: false,
    userImg: GuyImgTwo,
    userName: 'Username',
    status: false,
  },
];
