import { GuyImg, GuyImgTwo, UserImg, topUserImg, topUserThree } from 'assets/img';

import { TPeopleCard } from './../../components/shared/Cards/PeopleCard/types';

export const userSearchCase: TPeopleCard[] = [
  {
    id: 1,
    userImg: GuyImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 2,
    userImg: GuyImgTwo,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 3,
    userImg: UserImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 4,
    userImg: topUserImg,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 5,
    userImg: GuyImgTwo,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 6,
    userImg: UserImg,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 7,
    userStatus: false,
    userImg: topUserImg,
    userName: 'Username',
    status: false,
  },
  {
    id: 8,
    userImg: GuyImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 9,
    userStatus: true,
    userImg: GuyImgTwo,
    userName: 'Username',
    status: false,
  },
  {
    id: 10,
    userImg: UserImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 11,
    userStatus: false,
    userImg: topUserThree,
    userName: 'Username',
    status: false,
  },
  {
    id: 12,
    userImg: UserImg,
    userStatus: true,
    userName: 'Username',
    status: false,
  },
  {
    id: 13,
    userImg: GuyImg,
    userStatus: false,
    userName: 'Username',
    status: false,
  },
  {
    id: 14,
    userStatus: false,
    userName: 'Username',
    userImg: topUserThree,
    status: false,
  },
  {
    id: 15,
    userStatus: false,
    userImg: GuyImgTwo,
    userName: 'Username',
    status: false,
  },
];
