export const searchList = [
  { id: 1, value: 'Tournament Title Name, Montana, Eua' },
  { id: 2, value: 'Tournament Title Name, Montana, Eua' },
  { id: 3, value: 'Tournament Title Name, Montana, Eua' },
  { id: 4, value: 'Tournament Title Name, Montana, Eua' },
  { id: 5, value: 'Tournament Title Name, Montana, Eua' },
  { id: 6, value: 'Tournament Title Name, Montana, Eua' },
  { id: 7, value: 'Tournament Title Name, Montana, Eua' },
  { id: 8, value: 'Tournament Title Name, Montana, Eua' },
  { id: 9, value: 'Tournament Title Name, Montana, Eua' },
  { id: 10, value: 'Tournament Title Name, Montana, Eua' },
  { id: 11, value: 'Tournament Title Name, Montana, Eua' },
  { id: 12, value: 'Tournament Title Name, Montana, Eua' },
  { id: 13, value: 'Tournament Title Name, Montana, Eua' },
  { id: 14, value: 'Tournament Title Name, Montana, Eua' },
  { id: 15, value: 'Tournament Title Name, Montana, Eua' },
  { id: 16, value: 'Tournament Title Name, Montana, Eua' },
  { id: 17, value: 'Tournament Title Name, Montana, Eua' },
  { id: 18, value: 'Tournament Title Name, Montana, Eua' },
];
